name: Test
on: [pull_request]

jobs:
  integration-and-unit:
    name: Run integration and unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setting up tox environment
        uses: docker://kiwicom/tox:3.25.0
        env:
          TOXENV: ${{ matrix.toxenv }}
          XDG_CACHE_HOME: /tmp/cache
        with:
          args: >
            sh -c
            "
            mkdir -p reports ;
            apk add --no-cache cargo ;
            tox -e $TOXENV -- --junitxml=reports/$TOXENV/test_report.xml --cov-report xml --cov-config .coveragerc --cov-append --cov-report xml:reports/coverage.xml
            "
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: .tox
          key: ${{ runner.os }}-${{ hashFiles('poetry.lock') }}
    strategy:
      matrix:
        toxenv: [py37, py38, py39, py310]
